courses = ("Python", "Data Science", "Cloud Computing", "Cyber Security", "AI")
print("second course selected by student:", courses[1])
print("the last two courses:", courses[-2:])
print("is 'Python' present?", "Python" in courses)
print("index of Cloud Computing:", courses.index("Cloud Computing"))
print("total number of courses selected:", len(courses))
courses_updated = courses + ("Machine Learning", "Web Development")
print("new courses added:", courses_updated) 
courses_updated = tuple(x for x in courses_updated if x!= "Cyber Security")
print("without cyber security:", courses_updated)
sorted_courses = tuple(sorted(courses_updated))
print("sorted courses:", sorted_courses)
backup_courses = sorted_courses
print("backup courses:", backup_courses)
friend_courses = ("AI", "BlockChain", "Python")
combined_courses = courses_updated + friend_courses
print("combined courses:", combined_courses)
print("--- Final Summary ---")
print("final courses:", courses_updated)
print("sorted courses:", sorted_courses)
print("backup courses:", backup_courses)
print("combined courses:", combined_courses)
